### ISSUE TITLE
大佬，clover的HDMI好像不能用啊

### ISSUE THREAD

**Issue by Fan-0104** [wgggSg/OpenCore-For-DELL-5577#3]
热拔插重启，开机前插上显示无信号

**Comment by Fan-0104** [comment]
已经解决

**Comment by amadeusneko** [comment]
不好意思！！！没有注意到你的问题.......
请问你是修复了吗 qwq

**Comment by Fan-0104** [comment]
﻿嗯嗯，用的就是你去年九月份更新的那个方法；&nbsp;使用FB注入59160000；不知道630为啥不行，630热拔插还重启，外接还没反应。改成620的话，一定要在输入完登陆密码看到桌面后后再擦HDMI，要不然也不行。搞不懂啥原因😂😂交给大佬你了



发自我的iPhone

------------------ 原始邮件 ------------------
发件人: wgggKW <notifications@github.com&gt;
发送时间: 2020年6月9日 11:49
收件人: wgggSg/OpenCore-For-DELL-5577 <OpenCore-For-DELL-5577@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[wgggSg/OpenCore-For-DELL-5577] 大佬，clover的HDMI好像不能用啊 (#3)





 
不好意思！！！没有注意到你的问题.......
 请问你是修复了吗 qwq

**Comment by amadeusneko** [comment]
确实注入630比较玄学.....了解了！！
